/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'davidde' at '11/25/15 11:14 PM' with Gradle 2.6
 *
 * @author davidde, @date 11/25/15 11:14 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
